# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Layout/EndOfLine:
  EnforcedStyle: lf
Style/EvalWithLocation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
